name: Checkout, ESLint Checker, Test, Build
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: sudo npm ci
      - name: Run Unit tests
        run: npm test
        env:
          CI: true
      - name: Run E2E tests
        run: npm run e2e
        env:
          CI: true
      - name: Build
        run: npm run build --if-present
        env:
          CI: true
