name: Checkout, ESLint Checker, Test, Build
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: sudo npm ci
      - name: Check ESLint
        run: ng lint
      - name: Check Prettier
        run: prettier --config ./.prettierrc --list-different \"src/{app,environments}/**/*{.ts,.html,.scss}\""
      - name: Run Unit tests
        run: ng test --watch=false --browsers=ChromeHeadles
      - name: Run E2E tests
        run: ng e2e
      - name: Build
        run: ng build
