name: Checkout, ESLint Checker, Test, Build
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ESLint Checker
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: sudo npm ci
      - name: Run tests
        run: npm test
        env:
          CI: true
      - run: npm run build:production --if-present
