name: Checkout, ESLint Checker
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ESLint Checker
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
