name: Build, Test, and Deploy
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: ESLint Checker
        run: npm run lint
      - name: Build Production
        run: npm run build:production
      - name: Test
        run: npm run test
