name: Build, Test, and Deploy
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 12.x
      - name: ESLint Checker
        run: eslint . --ext .scss,.js,.html,.json,.ico,.svg
      - name: Build Production
        run: npm run build:production
      - name: Test
        run: npm run test
